# Python CircleCI 2.0 configuration file
version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7

        working_directory: ~/dionysus

        steps:
            - checkout

            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate

                    pip install -r requirements_dev.txt
                    pip install -r requirements.txt

                    mkdir test-results

            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    mkdir test-reports
                    pytest -v --cov=/home/circleci/dionysus/ --junitxml=../test-results/junit.xml
                    coverage xml

            - store_test_results:
                path: test-results
